addons:
   apt:
      update: true
      packages:
         - libnetfilter-queue-dev
dist: xenial
language: c
compiler:
   - clang
   - gcc
arch:
 -amd64
 -ppc64le
 
before_script:
   - mkdir build
script:
   - cd build
   - cmake ..
   - make -j2
