addons:
   apt:
      update: true
      packages:
         - libnetfilter-queue-dev
dist: xenial
language: c
arch:
 - amd64
 - ppc64le
 
compiler:
   - clang
   - gcc
before_script:
   - mkdir build
script:
   - cd build
   - cmake ..
   - make -j2
